name: DebugBuild
on:
  push:
    branches:
      - main

env:
  # 新しいソリューションファイルのパス
  SOLUTION_FILE_PATH: project/OriGine.sln
  # Visual Studio の構成 (Debug/Release)
  CONFIGURATION: Debug

jobs:
  build:
    runs-on: windows-latest

    steps:
      # リポジトリをクローン
      - name: Checkout
        uses: actions/checkout@v4

      # MSBuild をセットアップ
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      # 必要なディレクトリを作成
      - name: Create necessary directories
        run: |
          mkdir -p generated/obj/OriGine/Debug
          mkdir -p generated/outputs/Debug

      # 環境変数のデバッグ (オプション)
      - name: Debug Environment Variables
        run: |
          echo "Current Directory: $(pwd)"
          echo "SOLUTION_FILE_PATH=${{ env.SOLUTION_FILE_PATH }}"
          echo "CONFIGURATION=${{ env.CONFIGURATION }}"

      # ビルド
      - name: Build
        run: |
          msbuild ${{ env.SOLUTION_FILE_PATH }} /p:Platform=x64 /p:Configuration=${{ env.CONFIGURATION }} /p:SolutionDir=$(pwd)\
